name: iqp_kernel
kernel_params:
  alpha:
    type: range
    bounds: [0.0, 1.0]
    value_type: float
    log_scale: False

iqp_torch_device: 'cpu'
mod: 'lightning.gpu'
standardize: True

qq_inter: False

instance:
backend: